#!/bin/bash
# Sling slides


# Go to the directory
x=50-Tricks
echo "Updating slides $x ..."

# Create the presentation
cd ~/Projects/django-hammer/slides
cat ../doc/$x/Title ../doc/$x/Slides | 
template/bin/thumpSlides.py  > $x/$x.html 

# Run the presentation
w 50-Tricks/50-Tricks.html
#present

